import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'FCA Support',
  description: 'Generated by create next app',
  icons: {
    icon: {
      href: "https://theme.zdassets.com/theme_assets/1074739/17cf889da63b264cfb0734788a5e234d906a8175.png",
      url: "https://theme.zdassets.com/theme_assets/1074739/17cf889da63b264cfb0734788a5e234d906a8175.png"
    }
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
