/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewPickupRouteImport } from './routes/new-pickup'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PickupsIndexRouteImport } from './routes/pickups.index'
import { Route as PickupsIdRouteImport } from './routes/pickups.$id'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPickupRoute = NewPickupRouteImport.update({
  id: '/new-pickup',
  path: '/new-pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupsIndexRoute = PickupsIndexRouteImport.update({
  id: '/pickups/',
  path: '/pickups/',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupsIdRoute = PickupsIdRouteImport.update({
  id: '/pickups/$id',
  path: '/pickups/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/new-pickup': typeof NewPickupRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/pickups/$id': typeof PickupsIdRoute
  '/pickups/': typeof PickupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/new-pickup': typeof NewPickupRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/pickups/$id': typeof PickupsIdRoute
  '/pickups': typeof PickupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/new-pickup': typeof NewPickupRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/pickups/$id': typeof PickupsIdRoute
  '/pickups/': typeof PickupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/new-pickup'
    | '/settings'
    | '/sync'
    | '/pickups/$id'
    | '/pickups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/new-pickup'
    | '/settings'
    | '/sync'
    | '/pickups/$id'
    | '/pickups'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/new-pickup'
    | '/settings'
    | '/sync'
    | '/pickups/$id'
    | '/pickups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  NewPickupRoute: typeof NewPickupRoute
  SettingsRoute: typeof SettingsRoute
  SyncRoute: typeof SyncRoute
  PickupsIdRoute: typeof PickupsIdRoute
  PickupsIndexRoute: typeof PickupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-pickup': {
      id: '/new-pickup'
      path: '/new-pickup'
      fullPath: '/new-pickup'
      preLoaderRoute: typeof NewPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickups/': {
      id: '/pickups/'
      path: '/pickups'
      fullPath: '/pickups/'
      preLoaderRoute: typeof PickupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickups/$id': {
      id: '/pickups/$id'
      path: '/pickups/$id'
      fullPath: '/pickups/$id'
      preLoaderRoute: typeof PickupsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  NewPickupRoute: NewPickupRoute,
  SettingsRoute: SettingsRoute,
  SyncRoute: SyncRoute,
  PickupsIdRoute: PickupsIdRoute,
  PickupsIndexRoute: PickupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
