name: Release
on:
  push:
    branches:
      - "main"
jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PNPM Setup
        uses: pnpm/action-setup@v2
        with:
          version: 8.7.6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      # Node.js dependencies are in the admin directory
      - name: Install Node.js dependencies
        run: >
          pnpm install --frozen-lockfile

      # Run semantic-release with CI=true to abort husky
      - name: Run Semantic Release
        run: >
          CI=true npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
